baseURL = "https://bmeneg.com/"
languageCode = "en-us"
title = "bmeneg's blog"
theme = "xmin"
disqusShortname = "bmeneguele"
footnotereturnlinkcontents = "↩"
googleAnalytics = "UA-76416508-1"

[params]
description = "A website built through Hugo and blogdown."
footer = "[Github](https://github.com/bmeneguele) | [Twitter](https://twitter.com/bmeneguele)"

[permalinks]
posts = "/post/:slug"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "RSS"
url = "/index.xml"
